// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl8_Je-kFh9B8cbTAmA0YO4Vmbd3dAifg',
    appId: '1:157382504859:web:bac7428f5374f3739d713e',
    messagingSenderId: '157382504859',
    projectId: 'smart-chat-64cf9',
    authDomain: 'smart-chat-64cf9.firebaseapp.com',
    storageBucket: 'smart-chat-64cf9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAce0O4hnwFL8NRe8BqGVcNeM_EcmLYnKk',
    appId: '1:157382504859:android:1aea790b8239303d9d713e',
    messagingSenderId: '157382504859',
    projectId: 'smart-chat-64cf9',
    storageBucket: 'smart-chat-64cf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnr_vIZ-loR1ZThiK6y1QWs5jps4b8AjQ',
    appId: '1:157382504859:ios:1e2e6af5e3dac5fc9d713e',
    messagingSenderId: '157382504859',
    projectId: 'smart-chat-64cf9',
    storageBucket: 'smart-chat-64cf9.firebasestorage.app',
    iosBundleId: 'com.example.smartChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnr_vIZ-loR1ZThiK6y1QWs5jps4b8AjQ',
    appId: '1:157382504859:ios:1e2e6af5e3dac5fc9d713e',
    messagingSenderId: '157382504859',
    projectId: 'smart-chat-64cf9',
    storageBucket: 'smart-chat-64cf9.firebasestorage.app',
    iosBundleId: 'com.example.smartChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl8_Je-kFh9B8cbTAmA0YO4Vmbd3dAifg',
    appId: '1:157382504859:web:625aa72751f077f59d713e',
    messagingSenderId: '157382504859',
    projectId: 'smart-chat-64cf9',
    authDomain: 'smart-chat-64cf9.firebaseapp.com',
    storageBucket: 'smart-chat-64cf9.firebasestorage.app',
  );
}
